### ISSUE TITLE
Datos expuestos

### ISSUE THREAD

**Issue by fabriziotonin** [Magicmilian/rollingnews#1]
Los datos de usuario salen en la consola una
vez registrado
![image](https://user-images.githubusercontent.com/51201108/98135990-36071800-1e9f-11eb-99a5-8f9f97b8bb3b.png)

**Comment by Magicmilian** [comment]
### Solucionado.-

**Comentario:** 

> "Se habia optado por mostrar por consola los datos para evitar el warning de valores sin usar de React ya que actualmente no esta implementado en el backend la suscripcion real del usuario. Se eliminaron los reportes de consola para que la informacion no sea visible y se guardo la misma en un objeto a ser enviado en caso de implementacion del sistema de suscripcion en backend"
