### ISSUE TITLE
LogIn no funciona

### ISSUE THREAD

**Issue by fabriziotonin** [Magicmilian/rollingnews#2]
En logIn no puedo logearme, no poseo un nombre
de usuario o email , a demas de que en subscripcion no hay campo para la contraseña

![image](https://user-images.githubusercontent.com/51201108/98136205-71a1e200-1e9f-11eb-996b-1a858be2c066.png)

**Comment by Magicmilian** [comment]
@fabriziotonin El boton de suscribirse emula el registro de un usuario al boletin del portal de noticias. El boton de login es funcional solo para el usuario administrador ya que no se implemento la creacion de usuarios mediante el sitio web todavia.

Por lo tanto, mas que un issue de funcionalidad, podria definir este issue como **un problema de UX**, ya que quizas la mejor solucion hubiese sido definir una ruta para el login del admin que no sea accesible desde el contenido que ve el consumidor. 

El motivo de que se haya puesto este boton en el sitio web fue en realidad para no tener que comunicar la ruta a quien quiera ingresar como administrador en caso de revisiones, pero efectivamente podria ser mejorado.

**Comment by fabriziotonin** [comment]
En ese caso, lo mas conveniente seria ocultar ese botón subscripción  si es que no será funcional de momento e implementarlo cuando este este habilitado

**Comment by Magicmilian** [comment]
**Update**

Se añadio funcionalidad al boton de suscripcion. Al completar los campos correctamente, se envia un email de confirmacion de suscripcion al usuario al correo proporcionado por el mismo.
